---
 global:
  interval: 10
 dao:
  class: prefixlist.dao.PostgresDAO
  host: "localhost"
  dbname: "prefixlist"
  user: "emj"
  password: "emj"
 validation:
  default:
   violation_action: "deny"
  validators:
   -
    class: MemberASNValidator
    description: "Deny our local ASN"
    asns:
     - 43948
   -
    class: MemberASNValidator
    description: "Deny tier one operators"
    asns:
     - 1299
     - 2914
     - 3356
 rpsl_objects:
  - "AS-SPRITELINK"
  - "AS-CORE9"
